### ISSUE TITLE
不懂。。

### ISSUE THREAD

**Issue by ghost** [zhulinyv/nonebot_plugin_summon#1]
![EX94DIX R3H6 VZIW{1H}@V](https://user-images.githubusercontent.com/118903437/210168315-846116a2-7f66-4917-8fd5-659ec196e63f.png)

**Comment by zhulinyv** [comment]
> ![EX94DIX R3H6 VZIW{1H}@V](https://user-images.githubusercontent.com/118903437/210168315-846116a2-7f66-4917-8fd5-659ec196e63f.png)

已修复，请更新
若使用国内源 pip 安装，需要等一下，
可使用 `pip install nonebot-plugin-summon==1.1.1 -i https://pypi.tuna.tsinghua.edu.cn/simple` 或直接克隆本仓库安装。
